// @ts-nocheck
import { default as __fd_glob_70 } from "../content/docs/store/service/meta.json?collection=meta"
import { default as __fd_glob_69 } from "../content/docs/practice/install/meta.json?collection=meta"
import { default as __fd_glob_68 } from "../content/docs/practice/config/meta.json?collection=meta"
import { default as __fd_glob_67 } from "../content/docs/practice/advanced/meta.json?collection=meta"
import { default as __fd_glob_66 } from "../content/docs/store/account/meta.json?collection=meta"
import { default as __fd_glob_65 } from "../content/docs/panel/settings/meta.json?collection=meta"
import { default as __fd_glob_64 } from "../content/docs/panel/manage/meta.json?collection=meta"
import { default as __fd_glob_63 } from "../content/docs/panel/files/meta.json?collection=meta"
import { default as __fd_glob_62 } from "../content/docs/panel/config/meta.json?collection=meta"
import { default as __fd_glob_61 } from "../content/docs/panel/common/meta.json?collection=meta"
import { default as __fd_glob_60 } from "../content/docs/troubleshooting/meta.json?collection=meta"
import { default as __fd_glob_59 } from "../content/docs/practice/meta.json?collection=meta"
import { default as __fd_glob_58 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_57 from "../content/docs/store/service/upgrade-plan.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/store/service/upgrade-addon.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/store/service/renew-early.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/store/service/index.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/store/service/cancel-service.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/practice/install/plugin.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/practice/install/mod.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/practice/install/index.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/practice/config/worldguard.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/practice/config/server-properties.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/practice/config/plugin.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/practice/config/paper-global.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/practice/config/luckperms.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/practice/config/index.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/practice/config/economy.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/store/account/view-credit.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/store/account/share-account.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/store/account/reset-password.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/store/account/pay-credit.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/store/account/kyc.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/store/account/index.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/store/account/edit-account.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/store/account/add-credit.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/practice/advanced/proxy.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/practice/advanced/performance.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/practice/advanced/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/practice/advanced/database.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/practice/advanced/automation.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/panel/manage/upload.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/panel/manage/move.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/panel/manage/index.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/panel/manage/edit.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/panel/manage/backup.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/panel/config/user.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/panel/config/subdomain.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/panel/config/startup.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/panel/config/schedules.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/panel/config/index.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/panel/common/sftp.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/panel/common/settings.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/panel/common/index.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/panel/common/console.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/troubleshooting/traceroute.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/troubleshooting/nojar.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/troubleshooting/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/troubleshooting/chatgpt.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/quick-start/start-server.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/quick-start/order.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/quick-start/buying-guide.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/store/payment.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/store/link-discord.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/practice/subdomain.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/practice/index.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/practice/geyser.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/documents/terms-of-service.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/documents/privacy-policy.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/documents/1033-terms-of-service.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/index.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.doc("docs", "content/docs", {"index.mdx": __fd_glob_0, "documents/1033-terms-of-service.mdx": __fd_glob_1, "documents/privacy-policy.mdx": __fd_glob_2, "documents/terms-of-service.mdx": __fd_glob_3, "practice/geyser.mdx": __fd_glob_4, "practice/index.mdx": __fd_glob_5, "practice/subdomain.mdx": __fd_glob_6, "store/link-discord.mdx": __fd_glob_7, "store/payment.mdx": __fd_glob_8, "quick-start/buying-guide.mdx": __fd_glob_9, "quick-start/order.mdx": __fd_glob_10, "quick-start/start-server.mdx": __fd_glob_11, "troubleshooting/chatgpt.mdx": __fd_glob_12, "troubleshooting/index.mdx": __fd_glob_13, "troubleshooting/nojar.mdx": __fd_glob_14, "troubleshooting/traceroute.mdx": __fd_glob_15, "panel/common/console.mdx": __fd_glob_16, "panel/common/index.mdx": __fd_glob_17, "panel/common/settings.mdx": __fd_glob_18, "panel/common/sftp.mdx": __fd_glob_19, "panel/config/index.mdx": __fd_glob_20, "panel/config/schedules.mdx": __fd_glob_21, "panel/config/startup.mdx": __fd_glob_22, "panel/config/subdomain.mdx": __fd_glob_23, "panel/config/user.mdx": __fd_glob_24, "panel/manage/backup.mdx": __fd_glob_25, "panel/manage/edit.mdx": __fd_glob_26, "panel/manage/index.mdx": __fd_glob_27, "panel/manage/move.mdx": __fd_glob_28, "panel/manage/upload.mdx": __fd_glob_29, "practice/advanced/automation.mdx": __fd_glob_30, "practice/advanced/database.mdx": __fd_glob_31, "practice/advanced/index.mdx": __fd_glob_32, "practice/advanced/performance.mdx": __fd_glob_33, "practice/advanced/proxy.mdx": __fd_glob_34, "store/account/add-credit.mdx": __fd_glob_35, "store/account/edit-account.mdx": __fd_glob_36, "store/account/index.mdx": __fd_glob_37, "store/account/kyc.mdx": __fd_glob_38, "store/account/pay-credit.mdx": __fd_glob_39, "store/account/reset-password.mdx": __fd_glob_40, "store/account/share-account.mdx": __fd_glob_41, "store/account/view-credit.mdx": __fd_glob_42, "practice/config/economy.mdx": __fd_glob_43, "practice/config/index.mdx": __fd_glob_44, "practice/config/luckperms.mdx": __fd_glob_45, "practice/config/paper-global.mdx": __fd_glob_46, "practice/config/plugin.mdx": __fd_glob_47, "practice/config/server-properties.mdx": __fd_glob_48, "practice/config/worldguard.mdx": __fd_glob_49, "practice/install/index.mdx": __fd_glob_50, "practice/install/mod.mdx": __fd_glob_51, "practice/install/plugin.mdx": __fd_glob_52, "store/service/cancel-service.mdx": __fd_glob_53, "store/service/index.mdx": __fd_glob_54, "store/service/renew-early.mdx": __fd_glob_55, "store/service/upgrade-addon.mdx": __fd_glob_56, "store/service/upgrade-plan.mdx": __fd_glob_57, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_58, "practice/meta.json": __fd_glob_59, "troubleshooting/meta.json": __fd_glob_60, "panel/common/meta.json": __fd_glob_61, "panel/config/meta.json": __fd_glob_62, "panel/files/meta.json": __fd_glob_63, "panel/manage/meta.json": __fd_glob_64, "panel/settings/meta.json": __fd_glob_65, "store/account/meta.json": __fd_glob_66, "practice/advanced/meta.json": __fd_glob_67, "practice/config/meta.json": __fd_glob_68, "practice/install/meta.json": __fd_glob_69, "store/service/meta.json": __fd_glob_70, });